version: 2

dependencies:
  pre:
    - 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'

jobs:
  test:
    machine:
      node:
        version: 12.16.2
    steps:
      - run: rm -rf $CIRCLE_ARTIFACTS/coverage
      - run: npm run lint
      - run: npm run test
      - run: cp -r coverage $CIRCLE_ARTIFACTS
      - run: npm run coverage

  compile:
    machine:
      node:
        version: 12.16.2
    steps:
      - run: npm run build:node && npm run build:browser
