version: 2

machine:
  node:
    version: 12.16.2

dependencies:
  pre:
    - 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'

jobs:
  test:
    working_directory: ~/zoom
    docker:
      - image: node:10
    steps:
      - checkout
      - run: npm install
      - run: rm -rf $CIRCLE_ARTIFACTS/coverage
      - run: npm run lint
      - run: npm run test
      - run: cp -r coverage $CIRCLE_ARTIFACTS
      - run: npm run coverage

  build:
    working_directory: ~/zoom
    docker:
      - image: node:10
    steps:
      - checkout
      - run: npm install
      - run: npm run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
