version: 2

machine:
  node:
    version: 12.16.2

dependencies:
  pre:
    - 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'

jobs:
  test:
    machine: true
    steps:
      - run: rm -rf $CIRCLE_ARTIFACTS/coverage
      - run: npm run lint
      - run: npm run test
      - run: cp -r coverage $CIRCLE_ARTIFACTS
      - run: npm run coverage

  build:
    machine: true
    steps:
      - run: npm run build:node && npm run build:browser

workflows:
  version: 2
    build_and_test:
      jobs:
        - build
        - test:
            requires:
              - build
